name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm make mill git
      - uses: actions/checkout@v3.0.2
      - name: Test
        run: make test

  check_format:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm make mill git
      - uses: actions/checkout@v3
      - name: Test
        run: make checkformat

  publish:
    needs: [test, check_format]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    concurrency: publish-${{ github.sha }}
    container: archlinux/archlinux:latest
    environment: sonatype
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm make mill git
      - uses: actions/checkout@v3
        with:
          # checkout all history for vcs version detection
          fetch-depth: 0
      - name: Trust GitHub workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Publish
        run: make publish
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
